# Generated by Django 4.1.2 on 2023-11-13 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('companions', models.CharField(max_length=255)),
                ('travel_style', models.CharField(max_length=255)),
                ('travel_schedule', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
