# Generated by Django 4.1.2 on 2023-11-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_travelresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelresponse',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='travelresponse',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
