# Generated by Django 4.1.2 on 2023-11-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_description_traveldestination_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveldestination',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='traveldestination',
            name='image',
        ),
    ]
