# Generated by Django 4.1.2 on 2023-11-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_traveldestination_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelresponse',
            old_name='companions',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='travelresponse',
            old_name='travel_schedule',
            new_name='companion',
        ),
    ]
