# Generated by Django 4.1.2 on 2023-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_companions_travelresponse_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('preference', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('companion', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
            ],
        ),
    ]
